- id: '1707880928591'
  alias: Andy - Driving Flag Turn OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.andys_iphone_icv3
    to: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.andy_driving_flag
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.andy_driving_flag
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1707881038946'
  alias: Andy - Driving Flag Turn ON
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icv3_zone_distance") | float >
      2}}'
  condition:
  - condition: state
    entity_id: input_boolean.andy_far_away_flag
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.andy_driving_flag
  mode: single
- id: '1707881097642'
  alias: Andy - Far Away Flag, Turn OFF
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icv3_zone_distance") | float <=
      5}}'
  condition:
  - alias: Confirm Andy ZoneDistance:FromZone is home
    condition: state
    entity_id: sensor.andys_iphone_icv3_zone_distance
    attribute: from_zone
    state: home
    enabled: true
  - condition: state
    entity_id: input_boolean.andy_far_away_flag
    state: 'on'
  action:
  - alias: 'Andy Far Away Flag: Turn off'
    service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.andy_far_away_flag
  mode: single
- id: '1707881121463'
  alias: Andy - Far Away Flag, Turn ON
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icv3_zone_distance") | float >
      5}}'
  condition:
  - condition: state
    entity_id: input_boolean.andy_far_away_flag
    state: 'off'
  action:
  - alias: 'Andy Far Away Flag: Turn on'
    service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
      - input_boolean.andy_far_away_flag
  mode: single
- id: '1707881189661'
  alias: Andy - Open Garage when Arriving Home
  description: Open Garage when Arriving Home
  trigger:
  - platform: template
    value_template: '{{states("sensor.andys_iphone_icv3_zone_distance")  | float <=
      0.10}}'
  - platform: state
    entity_id:
    - sensor.andys_iphone_icv3_zone_name
    to: Home
  condition:
  - condition: state
    entity_id: input_boolean.andy_driving_flag
    state: 'on'
  action:
  - alias: execute automation depending if the time is not between 11pm - 7am
    if:
    - condition: time
      after: '23:00:00'
      before: 07:00:00
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
    then:
    - device_id: f5effe907501e33a98f058e89b009470
      domain: mobile_app
      type: notify
      message: Oi mate, it's a bit late and I wanted to make sure this doesn't run
        late at night on accident. Please open your garage manually.
      title: Just making sure!
      alias: Message Andy it's late to run the automation
    else:
    - alias: Send a message to Andy's phone via HA App
      data:
        title: Welcome home my Home from another... well you get the idea. Meditate
          - One love yo
        message: Come in my homie.
      action: notify.mobile_app_andys_iphone
    - alias: Open Garage
      data: {}
      enabled: true
      action: cover.open_cover
      target:
        entity_id: cover.garage_meross
  mode: single
- id: '1707881250652'
  alias: HA - Started Flag, Set
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:00:20
  - service: input_boolean.turn_on
    entity_id: input_boolean.ha_started_flag
  mode: single
- id: '1709904756835'
  alias: Master Bedroom Hue Dimmer - On Off Bedroom Fairy Lights
  description: ''
  trigger:
  - device_id: 1e8b183e7cce74d22c654caaf42be439
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: 6bc37d5e-d740-4639-992a-b0936abbfa85
  condition: []
  action:
  - service: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.master_bedroom_fairy_lights
  mode: single
- id: '1709956366094'
  alias: Master Bedroom Hue Dimmer Toggle Fairy Lights
  description: ''
  trigger:
  - device_id: 1e8b183e7cce74d22c654caaf42be439
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 04bdc157-8f03-4053-a474-e27caa0cb140
  condition: []
  action:
  - service: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.bedroom_hue_aumbiance_bulb_1
      - light.bedroom_hue_aumbiance_bulb_3
      - light.bedroom_hue_aumbiance_bulb_2
  mode: single
- id: '1709958185505'
  alias: Hue, Friends Of Hue switch, 4 button, all functions
  description: ''
  use_blueprint:
    path: MrBunbao/hue_dimmer_switch.yaml
    input:
      hue-switch-button1:
      - event.master_bedroom_hue_dimmer_button_1
      hue-switch-button2:
      - event.master_bedroom_hue_dimmer_button_2
      hue-switch-button3:
      - event.master_bedroom_hue_dimmer_button_3
      hue-switch-button4:
      - event.master_bedroom_hue_dimmer_button_4
- id: '1710001954743'
  alias: Shannon - Driving Flag Turn OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.shannons_iphone_icv3
    to: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.shannon_driving_flag
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      device_id: []
      area_id: []
      entity_id: input_boolean.shannon_driving_flag
    data: {}
  mode: single
- id: '1710001992963'
  alias: Shannon - Driving Flag Turn ON
  description: ''
  trigger:
  - platform: template
    value_template: '{{states("sensor.shannons_iphone_icv3_zone_distance") | float
      > 2}}'
  condition:
  - condition: state
    entity_id: input_boolean.shannon_far_away_flag
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.shannon_driving_flag
  mode: single
- id: '1710002020742'
  alias: Shannon - Far Away Flag, Turn OFF
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.shannons_iphone_icv3_zone_distance
    below: 5
  condition:
  - alias: Confirm Shannon ZoneDistance:FromZone is not home
    condition: state
    entity_id: sensor.shannons_iphone_icv3_zone_distance
    attribute: from_zone
    state: home
  action:
  - service: input_boolean.turn_off
    alias: 'Shannon Far Away Flag: Turn off'
    data: {}
    target:
      entity_id: input_boolean.shannon_far_away_flag
  mode: single
- id: '1710002037808'
  alias: Shannon - Far Away Flag, Turn ON
  description: ''
  trigger:
  - alias: When Shannon Zone Distance is above 5 mi
    platform: numeric_state
    entity_id:
    - sensor.shannons_iphone_icv3_zone_distance
    above: 5
  condition:
  - alias: Confirm Shannon ZoneDistance:FromZone is not home
    condition: state
    entity_id: sensor.shannons_iphone_icv3_zone_distance
    attribute: from_zone
    state: home
  action:
  - service: input_boolean.turn_on
    alias: 'Shannon Far Away Flag: Turn on'
    data: {}
    target:
      entity_id: input_boolean.shannon_far_away_flag
  mode: single
- id: '1714975183505'
  alias: Shannon - Open Garage when Arriving Home
  description: Open Garage when Arriving Home
  trigger:
  - platform: template
    value_template: '{{states("sensor.shannons_iphone_icv3_zone_distance")  | float
      <= 0.10}}'
  - platform: state
    entity_id:
    - sensor.shannons_iphone_icv3_zone_name
    to: Home
  condition:
  - condition: state
    entity_id: input_boolean.shannon_driving_flag
    state: 'on'
  action:
  - alias: execute automation depending if the time is not between 11pm - 7am
    if:
    - condition: time
      after: '23:00:00'
      before: 07:00:00
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
    then:
    - alias: Message Baby's - it's late to run the automation
      device_id: ea43a98b40abfb7c7c331ee5be5f2710
      domain: mobile_app
      type: notify
      title: It's late
      message: Sorry honey, can't open the garage just in case since it's late. Love
        you!
    else:
    - alias: Send a message to Baby's phone via HA App
      data:
        title: Welcome Home, Honey <3
        message: I LOOOOOVE YOU. WE GOING TO DISNEY SOON!
      action: notify.mobile_app_shannons_iphone
    - alias: Open Garage
      data: {}
      enabled: true
      action: cover.open_cover
      target:
        entity_id: cover.garage_meross
  mode: single
- id: '1715035793795'
  alias: Wash Done!
  description: ''
  use_blueprint:
    path: Blackshome/appliance-notifications.yaml
    input:
      power_sensor: sensor.washer_machine_power
      start_time_delay: 0.25
      running_dead_zone: 3
      include_start_notify: enable_start_notify_options
      start_notify_device:
      - f5effe907501e33a98f058e89b009470
      - ea43a98b40abfb7c7c331ee5be5f2710
      start_title: QUICK QUACK CLOTHES WASH HAS STARTED
      include_end_notify: enable_end_notify_options
      end_notify_device:
      - f5effe907501e33a98f058e89b009470
      - ea43a98b40abfb7c7c331ee5be5f2710
      end_message_title: Wash DONE!
      include_power_tracking: disable_power_tracking
      include_custom_actions: []
      end_custom_actions:
      - service: light.toggle
        metadata: {}
        data:
          rgb_color:
          - 235
          - 77
          - 61
          flash: long
        target:
          entity_id:
          - light.kitchen_chandelier
          - light.hue_play_bars
        enabled: false
      - service: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.kitchen_homepod_mini
          message: WASH DONE. Get your clothes before you leave it in the washer for
            the next 3 days.
        target:
          entity_id: tts.piper
        enabled: false
      start_appliance_power: 6
      end_appliance_power: 3
      start_custom_actions:
      - type: turn_on
        device_id: 76790cb9994d928fd1fbab5de7a9b4d9
        entity_id: a395d78db5e910af1ca4ab29bb049eff
        domain: remote
        enabled: false
      - service: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.kitchen_homepod_mini
          message: Your washer has ran. AWAY. Haha.
        target:
          entity_id: tts.piper
        enabled: false
      start_message: 'YES! Another load is IN! I’ll let you know when it’s finished
        - hopefully. I’m forgetful sometimes. '
      end_message: Yippee the washing machine is finished! Remember to put yourself
        in Drive, from Neutral!
      weekday_options:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sun
      - sat
- id: '1723069513540'
  alias: Tag Secret Garage Andy is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 5815a76f-692f-4ca4-acf9-44f221a57319
    id: ios.action_fired
  condition: []
  action:
  - action: cover.toggle
    metadata: {}
    data: {}
    target:
      entity_id: cover.garage_meross
    enabled: false
  - action: notify.mobile_app_andys_iphone
    metadata: {}
    data:
      title: Test
  mode: single
- id: '1723079758342'
  alias: 'Garage Shortcut iOS '
  description: ''
  trigger:
  - event_type: ios.action_fired
    event_data:
      actionID: 713801B2-612E-461F-9E6A-988E54199C6F
    platform: event
  condition: []
  action:
  - action: cover.toggle
    metadata: {}
    data: {}
    target:
      entity_id: cover.msg100_51a3_garage_door
  mode: single
- id: '1723165344719'
  alias: Garage Door Left Open Alert
  description: ''
  trigger:
  - platform: device
    device_id: ed97359f0b06e9f5a1572f3e870e0475
    domain: cover
    entity_id: 70e145bf10512e79c2159193e367513e
    type: opened
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - action: notify.mobile_app_andys_iphone
    metadata: {}
    data:
      message: The garage has been opened for at least 30 mins. You good?
      title: Garage Has Been Left Opened?
  - action: notify.mobile_app_shannons_iphone
    data:
      message: The garage has been opened for at least 30 mins. You good?
      title: Garage Has Been Left Opened? Also I love you. Hehe
  mode: single
